# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nemo
$menu = /home/kartavkun/.config/rofi/launchers/type-6/launcher.sh
$browser = zen-browser
