set -g mouse on
set -a terminal-features "xterm-kitty:cstyle"
set -g prefix C-a
set -g base-index 1
set -g renumber-windows on   
set -g mode-keys vi
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=black bg=white  "
set -g status-interval 5
set -g status-left "#S, #{keyboard_layout}"
set -g status-right ""
set -g allow-passthrough on
set -g allow-rename off

bind r source-file "~/.config/tmux/tmux.conf" \; display "Config reloaded!"
bind b set -g status
bind-key -n M-BSpace send-keys C-w
bind f run "tmux neww ~/.config/scripts/tmux-session-dispensary.sh"
# bind g run "~/.config/scripts/open-github.sh"
bind t run "tmux neww ~/.config/scripts/time.sh"
bind e run "~/.config/scripts/tmux-session-dispensary.sh ~/education/3rd_grade/2_semester"
# bind N run "~/.config/scripts/tmux-session-dispensary.sh ~/documents/notes"
# bind P run "~/.config/scripts/tmux-session-dispensary.sh ~/documents/projects"
bind D run "~/.config/scripts/tmux-session-dispensary.sh ~/.dotfiles/.config"
bind H run "~/.config/scripts/tmux-session-dispensary.sh ~"
# bind S run "~/.config/scripts/tmux-session-dispensary.sh ~/documents/projects/stormy"
bind G neww -n "git" -S lazygit
# bind o neww -S -n "BOOKMARKS" "nvim ~/bookmarks.csv"
# bind e neww -S "nvim ~/bookmarks.csv"
# bind E show-environment -g

bind -n C-1 select-window -t 1
bind -n C-2 select-window -t 2
bind -n C-3 select-window -t 3
bind -n C-4 select-window -t 4
bind -n C-5 select-window -t 5
bind -n C-6 select-window -t 6
bind -n C-7 select-window -t 7
bind -n C-8 select-window -t 8
bind -n C-9 select-window -t 9

# bind -n C-h select-pane -L
# bind -n C-l select-pane -R
# bind -n C-k select-pane -U
# bind -n C-j select-pane -D

bind -n C-S-h resize-pane -L 5
bind -n C-S-l resize-pane -R 5
bind -n C-S-k resize-pane -U 3
bind -n C-S-j resize-pane -D 3

bind h split-window -v
bind v split-window -h

bind -n C-Enter new-window
# bind -n C-c kill-pane
bind -n C-q kill-window
bind d detach

# bind -n M-l run 'clear'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'imomaliev/tmux-keyboard-layout'

run '~/.config/tmux/plugins/tpm/tpm'
