# ─────────────────────────
# FONT
# ─────────────────────────

font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 16.0
disable_ligatures never


# ─────────────────────────
# CURSOR
# ─────────────────────────

cursor_shape beam
cursor_blink_interval 0
cursor_stop_blinking_after 0
copy_on_select no

# ─────────────────────────
# WINDOW
# ─────────────────────────

window_padding_width 8
background_opacity 1.0

confirm_os_window_close 0
hide_window_decorations no

allow_remote_control yes

# ─────────────────────────
# TABS
# ─────────────────────────

tab_bar_edge top
tab_bar_style powerline
tab_bar_align left

tab_title_template "{title}"

# ─────────────────────────
# SCROLL
# ─────────────────────────

scrollback_lines 10000
wheel_scroll_multiplier 5.0

# ─────────────────────────
# SPLITS
# ─────────────────────────

enabled_layouts *
map ctrl+shift+enter new_window
map ctrl+shift+/ next_layout

map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down


# ─────────────────────────
# TABS
# ─────────────────────────

map ctrl+w new_tab
map ctrl+q close_tab
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab

# ─────────────────────────
# WINDOW MANAGEMENT
# ─────────────────────────

# map ctrl+shift+q close_window
map ctrl+shift+alt+r reload_config

# ─────────────────────────
# THEME
# ─────────────────────────
include Monokai.conf
